Adding Selector Section
columnflow/demo_docs pull request #3
Opened 2024-12-03 18:01 UTC by aalvesan

Hallo. I added most of the Selector section, not sure if there is anything missing or that we should add. I also fixed minor style things in calibrator and producer.

2025-01-13 10:33 UTC, pkausw requested changes
Sorry for the long wait, and thanks a lot for this PR @aalvesan ! Just found some minor typos mostly.

We could also move the itemized list with instructions how to solve the exercises into the exercise environments themselves. What do you think?

2025-01-13 10:33 UTC, pkausw commented on sections/selector.tex
> +Then, information that is dependent on the nanoAOD version is loaded. In this case, which MVA (Multi-Variate Analysis) flag should be used.
```suggestion
Then, information that is dependent on the nanoAOD version is loaded, in this case which MVA (Multi-Variate Analysis) flag should be used.
```

2025-01-13 10:33 UTC, pkausw commented on sections/selector.tex
> +Lastly, to perform four-vector calculations, we also recquire \code{attach\_coffea\_behavior}, which is imported at the beginning of the script from \code{columnflow.selection.util}.
```suggestion
Lastly, to perform four-vector calculations, we also require \code{attach\_coffea\_behavior}, which is imported at the beginning of the script from \code{columnflow.selection.util}.
```

2025-01-13 10:33 UTC, pkausw commented on sections/selector.tex
> +As mentioned in the last section, \code{sandbox} specifies the software enviorment where this \CCSPStlye{Selector} will be executed.
While this is a short and reasonable summary of these properties, it might also make sense to simply reference to the docs - we actually have a section on these keywords in the description of Selections

2025-01-13 10:33 UTC, pkausw commented on sections/selector.tex
> +            \item you recquire either a global or tracker muon (for tracker muons \code{nStations} should be a positive);
```suggestion
            \item you require either a global or tracker muon (for tracker muons \code{nStations} should be a positive);
```

2025-01-13 10:33 UTC, pkausw commented on sections/selector.tex
> +            \item discard standalone muon if the reconstructed tracks are only present in the muon system (i.e. for standalone muons, you should recquire a positive number of \code{nTrackerLayers});
```suggestion
            \item discard standalone muons if the reconstructed tracks are only present in the muon system (i.e. for standalone muons, you should require a positive number of \code{nTrackerLayers});
```

2025-01-24 09:58 UTC, aalvesan commented
Thanks for reviewing @pkausw ! All changes should be implemented now, can you please check and merge ?

2025-02-04 09:36 UTC, pkausw approved these changes

2025-02-04 09:36 UTC, merged